[versions]
# libraries
junit = "5.11.4"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.1.0"
kover = "0.8.3"
qodana = "2024.2.3"

[libraries]
junit = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
